"use client";

import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "../store/StoreProvider";
import Header from "./components/Header/Header/Header";
import SubHeader from "./components/Header/SubHeader/SubHeader";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSearchActive, setIsSearchActive] = useState(false);

  const toggleSearch = () => {
    setIsSearchActive(!isSearchActive);
  };

  return (
    <html lang="en" className="h-full">
      <head>
        <title>Ocala</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <StoreProvider>
          <div className="flex-1 flex flex-col">
            <Header onSearchToggle={toggleSearch} />
            <SubHeader isSearchActive={isSearchActive} />
            <main className="flex-1 bg-[var(--color-primary-lighter)]">{children}</main>
          </div>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
